---
######################### Pod #########################
# Documentation: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/
apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod # change to your pod name
#  namespace: work # change to your namespace
  labels:
    app.kubernetes.io/app: nginx # change to your app label
    app.kubernetes.io/version: 1.27.5 # never use :latest in production
spec:
#  initContainers:
#    - name: init-myservice
#      image: busybox
#      command: ['sh', '-c', 'echo Initializing...; sleep 5;']
#      resources:
#        requests:
#          memory: "64Mi"
#          cpu: "250m"
#        limits:
#          memory: "128Mi"
#          cpu: "500m"
  containers:
    - name: nginx # change to your container name
      image: nginx:1.27.5 # never use :latest in production
      ports:
        - containerPort: 80 
      resources:
        requests: # minimum resources required
          memory: "64Mi"
          cpu: "250m"
        limits: # maximum resources allowed
          memory: "128Mi"
          cpu: "500m"
      livenessProbe:
        tcpSocket: #(exec, httpGet, tcpSocket, grpc)
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 10