---
####################### Service ######################
#Documentation: https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
apiVersion: v1
kind: Service
metadata:
  name: test-st # change to your name
#  namespace: work
  labels: # service labels
    app.kubernetes.io/name: &name test-st # change to your name label
    app.kubernetes.io/instance: &instance test-st # change to your instance label
    app.kubernetes.io/version: &version v0.0.1 # change to your version label
spec:
  selector:   # managed pods labels
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *instance
    app.kubernetes.io/version: *version
  ports:
      - port: 80   #service port (src)
---
#################### Headless Service ####################
#Documentation: https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
apiVersion: v1
kind: Service
metadata:
  name: test-st-headless # change to your name
#  namespace: work
  labels: # service labels
    app.kubernetes.io/name: &name test-st # change to your name label
    app.kubernetes.io/instance: &instance test-st # change to your instance label
    app.kubernetes.io/version: &version v0.0.1 # change to your version label
spec:
  clusterIP: None # headless service
  selector:   # managed pods labels
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *instance
    app.kubernetes.io/version: *version
  ports:
      - port: 80   #service port (src)

---
###################### StatefulSet ####################
# Documentation: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/stateful-set-v1/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-st # change to your statefulset name
#  namespace: work # change to your namespace
  labels:
    app.kubernetes.io/name: &name test-st # change to your name label
    app.kubernetes.io/instance: &instance test-st # change to your instance label
    app.kubernetes.io/version: &version v0.0.1 # change to your version label
spec:
  serviceName: "test-st-headless" # change to your headless service name
  replicas: 3 # number of pod replicas
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
      app.kubernetes.io/instance: *instance
      app.kubernetes.io/version: *version
##################### Pod Template #####################
# This section is similar to a Pod manifest              
# Documentation: https://kubernetes.io/docs/concepts/workloads/pods/pod/ 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *name
        app.kubernetes.io/instance: *instance
        app.kubernetes.io/version: *version 
    spec:
      containers:
        - name: whoami # change to your container name
          image: traefick/whoami # never use :latest in production
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests: # minimum resources required
              memory: "64Mi"
              cpu: "250m"
            limits: # maximum resources allowed
              memory: "128Mi"
              cpu: "500m"