################### Job ###################
# Documentation: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/job-v1/
---
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob # change to your job name
#  namespace: work # change to your namespace
  labels:
    app.kubernetes.io/name: myjob # change to your app label
    app.kubernetes.io/version: v0.0.1 # change to your version label
spec:
#   selector: # optional, used to identify pods created by this job
#     matchLabels:
  template:
#    metadata:
#      labels:
    spec:
      restartPolicy: Never
      containers:
        - name: test-job
          image: busybox:1.28
          command: ["sh", "-c", "echo Test job running && sleep 10 && exit 0"]
          resources:
            requests: # minimum resources required
              memory: "32Mi"
              cpu: "100m"
            limits: # maximum resources allowed
              memory: "64Mi"
              cpu: "200m"

    