############# ConfigMap Manifest ###############
Documentation: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/config-map-v1/
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: app-Config
data:
#  TEST_DATABASE_HOST: "example.com"
#  TEST_DATABASE_PORT: "5432"