############### Secret Manifest ###############
# Documentation: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
StringData: # use StringData for plain text values (Kubernetes will encode them to base64)
  username: my-username
  password: my-password
#data: # use data for base64 encoded values
#  username: dXNlcm5hbWU=  # base64 encoded 'username'
#  password: cGFzc3dvcmQ=  # base64 encoded 'password'